# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

name: Continuous Integration

on:
  push:
    branches:
      - review_changes
jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: List files in directory
      run: ls -R

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: dodge_env
        environment-file: ./dodge/tests/environment.yml

    - name: Run tests
      shell: bash -l {0}
      run: python -m unittest